--------------------------------------------------------
-- Archivo creado  - lunes-junio-06-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table INICIO_CATEGORIA
--------------------------------------------------------

  CREATE TABLE "INICIO_CATEGORIA" 
   (	"IDCATEGORIA" NUMBER(11,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRECAT" NVARCHAR2(30)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INICIO_COMUNA
--------------------------------------------------------

  CREATE TABLE "INICIO_COMUNA" 
   (	"IDCOMUNA" NUMBER(11,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRECOM" NVARCHAR2(40)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INICIO_DETALLE
--------------------------------------------------------

  CREATE TABLE "INICIO_DETALLE" 
   (	"IDDETALLE" NUMBER(11,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CANTIDAD" NUMBER(11,0), 
	"SUBTOTAL" NUMBER(11,0), 
	"PRODUCTO_ID" NUMBER(11,0), 
	"VENTA_ID" NUMBER(11,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INICIO_DIRECCION
--------------------------------------------------------

  CREATE TABLE "INICIO_DIRECCION" 
   (	"IDDIRECCION" NUMBER(11,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DESCRIPCIONDIR" NCLOB, 
	"REGION_ID" NUMBER(11,0), 
	"USUARIO_ID" NVARCHAR2(15)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DESCRIPCIONDIR") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table INICIO_MARCA
--------------------------------------------------------

  CREATE TABLE "INICIO_MARCA" 
   (	"IDMARCA" NUMBER(11,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBREMARCA" NVARCHAR2(30)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INICIO_MODELO
--------------------------------------------------------

  CREATE TABLE "INICIO_MODELO" 
   (	"IDMODELO" NUMBER(11,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBREMODELO" NVARCHAR2(30), 
	"MARCA_ID" NUMBER(11,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INICIO_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "INICIO_PRODUCTO" 
   (	"IDPRODUCTO" NUMBER(11,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBREPRODUCTO" NVARCHAR2(50), 
	"PRECIOPRODUCTO" NUMBER(11,0), 
	"ESPECIFICACIONPROD" NVARCHAR2(900), 
	"STOCKPROD" NUMBER(11,0), 
	"IMAGENPROD" NVARCHAR2(100), 
	"MARCA_ID" NUMBER(11,0), 
	"TIPOPROD_ID" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INICIO_REGION
--------------------------------------------------------

  CREATE TABLE "INICIO_REGION" 
   (	"IDREGION" NUMBER(11,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBREREG" NVARCHAR2(40), 
	"COMUNA_ID" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INICIO_TIPOPROD
--------------------------------------------------------

  CREATE TABLE "INICIO_TIPOPROD" 
   (	"IDTIPOROD" NUMBER(11,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRETIPOPROD" NVARCHAR2(60)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INICIO_TIPOUSUARIO
--------------------------------------------------------

  CREATE TABLE "INICIO_TIPOUSUARIO" 
   (	"IDTIPOUSUARIO" NUMBER(11,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRETIPO" NVARCHAR2(30)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INICIO_USUARIO
--------------------------------------------------------

  CREATE TABLE "INICIO_USUARIO" 
   (	"USERNAME" NVARCHAR2(15), 
	"CONTRASENNIA" NVARCHAR2(30), 
	"NOMBRE" NVARCHAR2(60), 
	"APELLIDO" NVARCHAR2(60), 
	"EMAIL" NVARCHAR2(150), 
	"TIPOUSUARIO_ID" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INICIO_VENTA
--------------------------------------------------------

  CREATE TABLE "INICIO_VENTA" 
   (	"IDVENTA" NUMBER(11,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"FECHAVENTA" DATE, 
	"USUARIO_ID" NVARCHAR2(15)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

Insert into .INICIO_COMUNA (IDCOMUNA,NOMBRECOM) values ('1','Santiago');

Insert into .INICIO_DIRECCION (IDDIRECCION,REGION_ID,USUARIO_ID) values ('41','1','cheka');
Insert into .INICIO_DIRECCION (IDDIRECCION,REGION_ID,USUARIO_ID) values ('1','1','salas_si');
Insert into .INICIO_DIRECCION (IDDIRECCION,REGION_ID,USUARIO_ID) values ('21','1','invitado');

Insert into .INICIO_MARCA (IDMARCA,NOMBREMARCA) values ('1','Razer');
Insert into .INICIO_MARCA (IDMARCA,NOMBREMARCA) values ('2','HyperX');
Insert into .INICIO_MARCA (IDMARCA,NOMBREMARCA) values ('3','Fifine');
Insert into .INICIO_MARCA (IDMARCA,NOMBREMARCA) values ('4','Blue Yeti');
Insert into .INICIO_MARCA (IDMARCA,NOMBREMARCA) values ('43','SteelSeries');
Insert into .INICIO_MARCA (IDMARCA,NOMBREMARCA) values ('5','Asus');
Insert into .INICIO_MARCA (IDMARCA,NOMBREMARCA) values ('21','Redragon');
Insert into .INICIO_MARCA (IDMARCA,NOMBREMARCA) values ('22','Cougar');
Insert into .INICIO_MARCA (IDMARCA,NOMBREMARCA) values ('41','Logitech');
Insert into .INICIO_MARCA (IDMARCA,NOMBREMARCA) values ('42','corsair');
Insert into .INICIO_MARCA (IDMARCA,NOMBREMARCA) values ('44','Asus');
Insert into .INICIO_MARCA (IDMARCA,NOMBREMARCA) values ('61','Zotac');
Insert into .INICIO_MARCA (IDMARCA,NOMBREMARCA) values ('62','Msi');
Insert into .INICIO_MARCA (IDMARCA,NOMBREMARCA) values ('63','Aorus');
Insert into .INICIO_MARCA (IDMARCA,NOMBREMARCA) values ('64','EVGA');
Insert into .INICIO_MARCA (IDMARCA,NOMBREMARCA) values ('65','Intel');
Insert into .INICIO_MARCA (IDMARCA,NOMBREMARCA) values ('66','AMD');

Insert into .INICIO_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,ESPECIFICACIONPROD,STOCKPROD,IMAGENPROD,MARCA_ID,TIPOPROD_ID) values ('166','AORUS RGB GP DDR4 16GB','28900','Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis quia deserunt corporis accusamus impedit doloremque ipsam modi itaque nemo neque commodi in aliquam perferendis, labore quos expedita architecto error perspiciatis!','2','productos/rams_aorus.png','63','4');
Insert into .INICIO_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,ESPECIFICACIONPROD,STOCKPROD,IMAGENPROD,MARCA_ID,TIPOPROD_ID) values ('2','HyperX Quadcast S RGB','100001','El HyperX QuadCast es el micr?fono independiente todo incluido ideal para el aspirante a streamer o                 podcaster que busca un micr?fono de condensador con sonido de calidad. QuadCast viene con su propio                 soporte antivibraciones para ayudar a reducir los ruidos de la vida diaria y un filtro pop incorporado                 para amortiguar los molestos sonidos explosivos.','12','productos/quad.jpg','2','1');
Insert into .INICIO_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,ESPECIFICACIONPROD,STOCKPROD,IMAGENPROD,MARCA_ID,TIPOPROD_ID) values ('1','Razer Seriren Mini','47200','Con el micr?fono Razer descubrir?s una nueva forma de captar y emitir audios                 Fiel reflejo de la realidad, ideal para varias actividadesz, te brindar? un sonido de calidad y conseguir?s la nitidez de las voces.','10','productos/seireni.jpg','1','1');
Insert into .INICIO_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,ESPECIFICACIONPROD,STOCKPROD,IMAGENPROD,MARCA_ID,TIPOPROD_ID) values ('3','Fifine K669B','37990','Con el micr?fono Fifine descubrir?s una nueva forma de captar y emitir audios.                 Fiel reflejo de la realidad                 Ideal para varias actividades. Te brindar? un sonido de calidad y conseguir?s la nitidez de las voces.','10','productos/fifain.jpg','3','1');
Insert into .INICIO_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,ESPECIFICACIONPROD,STOCKPROD,IMAGENPROD,MARCA_ID,TIPOPROD_ID) values ('4','Hyper X Solocast','49990','Con el micr?fono HyperX descubrir?s una nueva forma de captar y emitir audios.                 Fiel reflejo de la realidad                 Ideal para varias actividades. Te brindar? un sonido de calidad y conseguir?s la nitidez de las voces.','10','productos/soloqi.jpg','2','1');
Insert into .INICIO_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,ESPECIFICACIONPROD,STOCKPROD,IMAGENPROD,MARCA_ID,TIPOPROD_ID) values ('5','Blue Yeti Snowball','35990','La comunicaci?n clara y poderosa es importante para todas las organizaciones. Los micr?fonos de Blue te                 permiten capturar y transmitir con una calidad de sonido sorprendente. Blue combina audio de calidad                 profesional con la simplicidad plug-and-play para ofrecer un rendimiento que est? a a?os luz de los                 micr?fonos integrados para port?tiles y c?maras.','10','productos/snowball.png','4','1');
Insert into .INICIO_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,ESPECIFICACIONPROD,STOCKPROD,IMAGENPROD,MARCA_ID,TIPOPROD_ID) values ('6','Blue Yeti Multipatron','89790','La comunicaci?n clara y poderosa es importante para todas las organizaciones. Los micr?fonos de Blue te                 permiten capturar y transmitir con una calidad de sonido sorprendente. Blue combina audio de calidad                 profesional con la simplicidad plug-and-play para ofrecer un rendimiento que est? a a?os luz de los                 micr?fonos integrados para port?tiles y c?maras.','10','productos/Blueyetii.png','4','1');
Insert into .INICIO_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,ESPECIFICACIONPROD,STOCKPROD,IMAGENPROD,MARCA_ID,TIPOPROD_ID) values ('7','Fifine Ampligame','78490','Sus caracter?sticas son su excelente sonido, con touch para darle silenciar el micr?fono y adem?s cuenta con RGB.                 Trae su propio tr?pode y adem?s cuenta con un cable USB hacia el computador y conexi?n tipo C hacia el micr?fono','10','productos/ampligame.png','3','1');
Insert into .INICIO_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,ESPECIFICACIONPROD,STOCKPROD,IMAGENPROD,MARCA_ID,TIPOPROD_ID) values ('8','Hyper X Quadcast RED','84990','Con el micr?fono HyperX descubrir?s una nueva forma de captar y emitir audios.                 Fiel reflejo de la realidad                 Ideal para varias actividades. Te brindar? un sonido de calidad y conseguir?s la nitidez de las voces.','10','productos/quadcastrojo_5gOLldr.png','2','1');
Insert into .INICIO_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,ESPECIFICACIONPROD,STOCKPROD,IMAGENPROD,MARCA_ID,TIPOPROD_ID) values ('122','Logitech G503 KDA','45990','Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis quia deserunt corporis accusamus impedit doloremque ipsam modi itaque nemo neque commodi in aliquam perferendis, labore quos expedita architecto error perspiciatis!','10','productos/kda.png','41','5');
Insert into .INICIO_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,ESPECIFICACIONPROD,STOCKPROD,IMAGENPROD,MARCA_ID,TIPOPROD_ID) values ('64','Hyperx allow fps','9900','Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nobis, tempora praesentium consequatur cum porro quas numquam modi ex vel quo, quasi consequuntur deleniti voluptate architecto, repellendus nam deserunt. Explicabo, quo?','12','productos/alloy_fps.png','2','2');
Insert into .INICIO_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,ESPECIFICACIONPROD,STOCKPROD,IMAGENPROD,MARCA_ID,TIPOPROD_ID) values ('121','Cougar MinosXT','34990','Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis quia deserunt corporis accusamus impedit doloremque ipsam modi itaque nemo neque commodi in aliquam perferendis, labore quos expedita architecto error perspiciatis!','10','productos/cougar_minosxt.png','22','5');
Insert into .INICIO_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,ESPECIFICACIONPROD,STOCKPROD,IMAGENPROD,MARCA_ID,TIPOPROD_ID) values ('101','Razer BlackWidow','57990','Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis quia deserunt corporis accusamus impedit doloremque ipsam modi itaque nemo neque commodi in aliquam perferendis, labore quos expedita architecto error perspiciatis!','10','productos/black_widow.png','1','2');
Insert into .INICIO_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,ESPECIFICACIONPROD,STOCKPROD,IMAGENPROD,MARCA_ID,TIPOPROD_ID) values ('123','Rog Gladuis PInk','45990','Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis quia deserunt corporis accusamus impedit doloremque ipsam modi itaque nemo neque commodi in aliquam perferendis, labore quos expedita architecto error perspiciatis!','9','productos/rog_gladius_LpZmwlV.png','44','5');
Insert into .INICIO_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,ESPECIFICACIONPROD,STOCKPROD,IMAGENPROD,MARCA_ID,TIPOPROD_ID) values ('102','Redragon Kumara k552','45990','Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis quia deserunt corporis accusamus impedit doloremque ipsam modi itaque nemo neque commodi in aliquam perferendis, labore quos expedita architecto error perspiciatis!','7','productos/k552_GqlmgaR.png','21','2');
Insert into .INICIO_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,ESPECIFICACIONPROD,STOCKPROD,IMAGENPROD,MARCA_ID,TIPOPROD_ID) values ('141','Aorus RTX 3090','2999990','Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis quia deserunt corporis accusamus impedit doloremque ipsam modi itaque nemo neque commodi in aliquam perferendis, labore quos expedita architecto error perspiciatis!','2','productos/3090_Jdxyrj7.png','63','3');
Insert into .INICIO_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,ESPECIFICACIONPROD,STOCKPROD,IMAGENPROD,MARCA_ID,TIPOPROD_ID) values ('142','EVGA 2080TI','1499990','Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis quia deserunt corporis accusamus impedit doloremque ipsam modi itaque nemo neque commodi in aliquam perferendis, labore quos expedita architecto error perspiciatis!','4','productos/2080_evga.png','64','3');
Insert into .INICIO_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,ESPECIFICACIONPROD,STOCKPROD,IMAGENPROD,MARCA_ID,TIPOPROD_ID) values ('143','Zotac  GTX1650','359990','Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis quia deserunt corporis accusamus impedit doloremque ipsam modi itaque nemo neque commodi in aliquam perferendis, labore quos expedita architecto error perspiciatis!','9','productos/1650zotac.png','61','3');
Insert into .INICIO_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,ESPECIFICACIONPROD,STOCKPROD,IMAGENPROD,MARCA_ID,TIPOPROD_ID) values ('161','Intel i7-12600k','699990','Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis quia deserunt corporis accusamus impedit doloremque ipsam modi itaque nemo neque commodi in aliquam perferendis, labore quos expedita architecto error perspiciatis!','3','productos/i7_12i.png','65','6');
Insert into .INICIO_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,ESPECIFICACIONPROD,STOCKPROD,IMAGENPROD,MARCA_ID,TIPOPROD_ID) values ('162','AMD Ryzen 7 5800x','497990','Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis quia deserunt corporis accusamus impedit doloremque ipsam modi itaque nemo neque commodi in aliquam perferendis, labore quos expedita architecto error perspiciatis!','3','productos/ryzen_7i.png','66','6');
Insert into .INICIO_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,ESPECIFICACIONPROD,STOCKPROD,IMAGENPROD,MARCA_ID,TIPOPROD_ID) values ('163','Intel i5-10400','290990','Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis quia deserunt corporis accusamus impedit doloremque ipsam modi itaque nemo neque commodi in aliquam perferendis, labore quos expedita architecto error perspiciatis!','4','productos/intel_i5.png','65','6');
Insert into .INICIO_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,ESPECIFICACIONPROD,STOCKPROD,IMAGENPROD,MARCA_ID,TIPOPROD_ID) values ('164','HyperX Fury DDR4 8GB','45990','Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis quia deserunt corporis accusamus impedit doloremque ipsam modi itaque nemo neque commodi in aliquam perferendis, labore quos expedita architecto error perspiciatis!','5','productos/jaiperxxxxx.png','2','4');
Insert into .INICIO_PRODUCTO (IDPRODUCTO,NOMBREPRODUCTO,PRECIOPRODUCTO,ESPECIFICACIONPROD,STOCKPROD,IMAGENPROD,MARCA_ID,TIPOPROD_ID) values ('165','HyperX Fury DDR4 16GB RGB','140990','Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis quia deserunt corporis accusamus impedit doloremque ipsam modi itaque nemo neque commodi in aliquam perferendis, labore quos expedita architecto error perspiciatis!','6','productos/rams_hyperx.png','2','4');

Insert into .INICIO_REGION (IDREGION,NOMBREREG,COMUNA_ID) values ('1','Metropolitana','1');

Insert into .INICIO_TIPOPROD (IDTIPOROD,NOMBRETIPOPROD) values ('1','Microfono');
Insert into .INICIO_TIPOPROD (IDTIPOROD,NOMBRETIPOPROD) values ('2','Teclado');
Insert into .INICIO_TIPOPROD (IDTIPOROD,NOMBRETIPOPROD) values ('3','Grafica');
Insert into .INICIO_TIPOPROD (IDTIPOROD,NOMBRETIPOPROD) values ('4','Ram');
Insert into .INICIO_TIPOPROD (IDTIPOROD,NOMBRETIPOPROD) values ('5','Mouse');
Insert into .INICIO_TIPOPROD (IDTIPOROD,NOMBRETIPOPROD) values ('6','Procesador');

Insert into .INICIO_TIPOUSUARIO (IDTIPOUSUARIO,NOMBRETIPO) values ('1','admin');
Insert into .INICIO_TIPOUSUARIO (IDTIPOUSUARIO,NOMBRETIPO) values ('2','usuario');

Insert into .INICIO_USUARIO (USERNAME,CONTRASENNIA,NOMBRE,APELLIDO,EMAIL,TIPOUSUARIO_ID) values ('cheka','12345','Carloswfwfw','fabres','carlos@sexologo.com','2');
Insert into .INICIO_USUARIO (USERNAME,CONTRASENNIA,NOMBRE,APELLIDO,EMAIL,TIPOUSUARIO_ID) values ('salas_si','2222','salas','gei','saasdasd@asdasd.com','2');
Insert into .INICIO_USUARIO (USERNAME,CONTRASENNIA,NOMBRE,APELLIDO,EMAIL,TIPOUSUARIO_ID) values ('admin','admin','admin','admin','admin@admin.com','1');
Insert into .INICIO_USUARIO (USERNAME,CONTRASENNIA,NOMBRE,APELLIDO,EMAIL,TIPOUSUARIO_ID) values ('invitado','invitado','invitado','invitado','invitado@invitado.com','2');

----------------------------

TIENES QUE AGREGAR El
commit;


----------------------
--------------------------------------------------------
--  DDL for Index SYS_C0011505
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011505" ON "INICIO_CATEGORIA" ("IDCATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011507
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011507" ON "INICIO_COMUNA" ("IDCOMUNA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011540
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011540" ON "INICIO_DETALLE" ("IDDETALLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INICIO_DET_PRODUCTO_I_0023C3B4
--------------------------------------------------------

  CREATE INDEX "INICIO_DET_PRODUCTO_I_0023C3B4" ON "INICIO_DETALLE" ("PRODUCTO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INICIO_DET_VENTA_ID_50CBE654
--------------------------------------------------------

  CREATE INDEX "INICIO_DET_VENTA_ID_50CBE654" ON "INICIO_DETALLE" ("VENTA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INICIO_DIR_REGION_ID_2A8FE6B1
--------------------------------------------------------

  CREATE INDEX "INICIO_DIR_REGION_ID_2A8FE6B1" ON "INICIO_DIRECCION" ("REGION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011534
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011534" ON "INICIO_DIRECCION" ("IDDIRECCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INICIO_DIR_USUARIO_ID_598A3257
--------------------------------------------------------

  CREATE INDEX "INICIO_DIR_USUARIO_ID_598A3257" ON "INICIO_DIRECCION" ("USUARIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011509
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011509" ON "INICIO_MARCA" ("IDMARCA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011531
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011531" ON "INICIO_MODELO" ("IDMODELO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INICIO_MOD_MARCA_ID_73855542
--------------------------------------------------------

  CREATE INDEX "INICIO_MOD_MARCA_ID_73855542" ON "INICIO_MODELO" ("MARCA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011528
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011528" ON "INICIO_PRODUCTO" ("IDPRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INICIO_PRO_MARCA_ID_A04BEEDA
--------------------------------------------------------

  CREATE INDEX "INICIO_PRO_MARCA_ID_A04BEEDA" ON "INICIO_PRODUCTO" ("MARCA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INICIO_PRO_TIPOPROD_I_98BB12C9
--------------------------------------------------------

  CREATE INDEX "INICIO_PRO_TIPOPROD_I_98BB12C9" ON "INICIO_PRODUCTO" ("TIPOPROD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011522
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011522" ON "INICIO_REGION" ("IDREGION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INICIO_REG_COMUNA_ID_DBD35DE5
--------------------------------------------------------

  CREATE INDEX "INICIO_REG_COMUNA_ID_DBD35DE5" ON "INICIO_REGION" ("COMUNA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011511
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011511" ON "INICIO_TIPOPROD" ("IDTIPOROD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011513
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011513" ON "INICIO_TIPOUSUARIO" ("IDTIPOUSUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011516
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011516" ON "INICIO_USUARIO" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INICIO_USU_TIPOUSUARI_CC956262
--------------------------------------------------------

  CREATE INDEX "INICIO_USU_TIPOUSUARI_CC956262" ON "INICIO_USUARIO" ("TIPOUSUARIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011520
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011520" ON "INICIO_VENTA" ("IDVENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INICIO_VEN_USUARIO_ID_81C581B1
--------------------------------------------------------

  CREATE INDEX "INICIO_VEN_USUARIO_ID_81C581B1" ON "INICIO_VENTA" ("USUARIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table INICIO_CATEGORIA
--------------------------------------------------------

  ALTER TABLE "INICIO_CATEGORIA" MODIFY ("IDCATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "INICIO_CATEGORIA" ADD PRIMARY KEY ("IDCATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INICIO_COMUNA
--------------------------------------------------------

  ALTER TABLE "INICIO_COMUNA" MODIFY ("IDCOMUNA" NOT NULL ENABLE);
  ALTER TABLE "INICIO_COMUNA" ADD PRIMARY KEY ("IDCOMUNA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INICIO_DETALLE
--------------------------------------------------------

  ALTER TABLE "INICIO_DETALLE" MODIFY ("IDDETALLE" NOT NULL ENABLE);
  ALTER TABLE "INICIO_DETALLE" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "INICIO_DETALLE" MODIFY ("SUBTOTAL" NOT NULL ENABLE);
  ALTER TABLE "INICIO_DETALLE" MODIFY ("PRODUCTO_ID" NOT NULL ENABLE);
  ALTER TABLE "INICIO_DETALLE" MODIFY ("VENTA_ID" NOT NULL ENABLE);
  ALTER TABLE "INICIO_DETALLE" ADD PRIMARY KEY ("IDDETALLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INICIO_DIRECCION
--------------------------------------------------------

  ALTER TABLE "INICIO_DIRECCION" MODIFY ("IDDIRECCION" NOT NULL ENABLE);
  ALTER TABLE "INICIO_DIRECCION" MODIFY ("USUARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "INICIO_DIRECCION" ADD PRIMARY KEY ("IDDIRECCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INICIO_MARCA
--------------------------------------------------------

  ALTER TABLE "INICIO_MARCA" MODIFY ("IDMARCA" NOT NULL ENABLE);
  ALTER TABLE "INICIO_MARCA" ADD PRIMARY KEY ("IDMARCA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INICIO_MODELO
--------------------------------------------------------

  ALTER TABLE "INICIO_MODELO" MODIFY ("IDMODELO" NOT NULL ENABLE);
  ALTER TABLE "INICIO_MODELO" MODIFY ("MARCA_ID" NOT NULL ENABLE);
  ALTER TABLE "INICIO_MODELO" ADD PRIMARY KEY ("IDMODELO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INICIO_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "INICIO_PRODUCTO" MODIFY ("IDPRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "INICIO_PRODUCTO" MODIFY ("PRECIOPRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "INICIO_PRODUCTO" MODIFY ("STOCKPROD" NOT NULL ENABLE);
  ALTER TABLE "INICIO_PRODUCTO" MODIFY ("MARCA_ID" NOT NULL ENABLE);
  ALTER TABLE "INICIO_PRODUCTO" MODIFY ("TIPOPROD_ID" NOT NULL ENABLE);
  ALTER TABLE "INICIO_PRODUCTO" ADD PRIMARY KEY ("IDPRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INICIO_REGION
--------------------------------------------------------

  ALTER TABLE "INICIO_REGION" MODIFY ("IDREGION" NOT NULL ENABLE);
  ALTER TABLE "INICIO_REGION" ADD PRIMARY KEY ("IDREGION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INICIO_TIPOPROD
--------------------------------------------------------

  ALTER TABLE "INICIO_TIPOPROD" MODIFY ("IDTIPOROD" NOT NULL ENABLE);
  ALTER TABLE "INICIO_TIPOPROD" ADD PRIMARY KEY ("IDTIPOROD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INICIO_TIPOUSUARIO
--------------------------------------------------------

  ALTER TABLE "INICIO_TIPOUSUARIO" MODIFY ("IDTIPOUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "INICIO_TIPOUSUARIO" ADD PRIMARY KEY ("IDTIPOUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INICIO_USUARIO
--------------------------------------------------------

  ALTER TABLE "INICIO_USUARIO" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "INICIO_USUARIO" MODIFY ("TIPOUSUARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "INICIO_USUARIO" ADD PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INICIO_VENTA
--------------------------------------------------------

  ALTER TABLE "INICIO_VENTA" MODIFY ("IDVENTA" NOT NULL ENABLE);
  ALTER TABLE "INICIO_VENTA" MODIFY ("FECHAVENTA" NOT NULL ENABLE);
  ALTER TABLE "INICIO_VENTA" MODIFY ("USUARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "INICIO_VENTA" ADD PRIMARY KEY ("IDVENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INICIO_DETALLE
--------------------------------------------------------

  ALTER TABLE "INICIO_DETALLE" ADD CONSTRAINT "INICIO_DE_PRODUCTO__0023C3B4_F" FOREIGN KEY ("PRODUCTO_ID")
	  REFERENCES "INICIO_PRODUCTO" ("IDPRODUCTO") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "INICIO_DETALLE" ADD CONSTRAINT "INICIO_DE_VENTA_ID_50CBE654_F" FOREIGN KEY ("VENTA_ID")
	  REFERENCES "INICIO_VENTA" ("IDVENTA") DEFERRABLE INITIALLY DEFERRED ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INICIO_DIRECCION
--------------------------------------------------------

  ALTER TABLE "INICIO_DIRECCION" ADD CONSTRAINT "INICIO_DI_REGION_ID_2A8FE6B1_F" FOREIGN KEY ("REGION_ID")
	  REFERENCES "INICIO_REGION" ("IDREGION") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "INICIO_DIRECCION" ADD CONSTRAINT "INICIO_DI_USUARIO_I_598A3257_F" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "INICIO_USUARIO" ("USERNAME") DEFERRABLE INITIALLY DEFERRED ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INICIO_MODELO
--------------------------------------------------------

  ALTER TABLE "INICIO_MODELO" ADD CONSTRAINT "INICIO_MO_MARCA_ID_73855542_F" FOREIGN KEY ("MARCA_ID")
	  REFERENCES "INICIO_MARCA" ("IDMARCA") DEFERRABLE INITIALLY DEFERRED ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INICIO_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "INICIO_PRODUCTO" ADD CONSTRAINT "INICIO_PR_MARCA_ID_A04BEEDA_F" FOREIGN KEY ("MARCA_ID")
	  REFERENCES "INICIO_MARCA" ("IDMARCA") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "INICIO_PRODUCTO" ADD CONSTRAINT "INICIO_PR_TIPOPROD__98BB12C9_F" FOREIGN KEY ("TIPOPROD_ID")
	  REFERENCES "INICIO_TIPOPROD" ("IDTIPOROD") DEFERRABLE INITIALLY DEFERRED ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INICIO_REGION
--------------------------------------------------------

  ALTER TABLE "INICIO_REGION" ADD CONSTRAINT "INICIO_RE_COMUNA_ID_DBD35DE5_F" FOREIGN KEY ("COMUNA_ID")
	  REFERENCES "INICIO_COMUNA" ("IDCOMUNA") DEFERRABLE INITIALLY DEFERRED ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INICIO_USUARIO
--------------------------------------------------------

  ALTER TABLE "INICIO_USUARIO" ADD CONSTRAINT "INICIO_US_TIPOUSUAR_CC956262_F" FOREIGN KEY ("TIPOUSUARIO_ID")
	  REFERENCES "INICIO_TIPOUSUARIO" ("IDTIPOUSUARIO") DEFERRABLE INITIALLY DEFERRED ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INICIO_VENTA
--------------------------------------------------------

  ALTER TABLE "INICIO_VENTA" ADD CONSTRAINT "INICIO_VE_USUARIO_I_81C581B1_F" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "INICIO_USUARIO" ("USERNAME") DEFERRABLE INITIALLY DEFERRED ENABLE;
